disabled_rules:
  - line_length # Line length should not be a warning, come on
  - trailing_comma # This fights with other formatters
  - type_body_length # We might re-enable this as we get better

excluded:
  - .build # Way too much random crap ends up in here to lint
  - Packages # We can't trust others to meet our exacting standards

check_for_updates: true
